services:
  onboarding-web-local:
    container_name: onboarding-web-local
    build:
      context: .
      target: development
    env_file:
      - ./docker/env/local.env
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
